greedy: util.c greedy.c
		gcc util.c queue.c greedy.c -std=c99 -o ../build/greedy.out

enumerate: util.c enumerate.c
		gcc util.c queue.c enumerate.c -std=c99 -o ../build/enumerate.out

2opt: util.c 2opt.c
		gcc util.c queue.c 2opt.c -std=c99 -o ../build/2opt.out

SA_2opt: util.c SA_2opt.c
		gcc util.c queue.c SA_2opt.c -std=c99 -o ../build/SA_2opt.out -lm
