ghost: util.c ghost.c
	gcc util.c queue.c ghost.c -o ../build/ghost.out -std=c99
pacman: util.c pacman.c
	gcc util.c pacman.c bits/graph.c bits/queue.c bits/search.c bits/methods.c -std=c99 -o ../build/simple.out

