dfs: dfs.c util.c
	gcc util.c dfs.c -std=c99 -o ../build/dfs.out

bfs: bfs.c util.c
	gcc util.c bfs.c -std=c99 -o ../build/bfs.out

dijkstra: dijkstra.c util.c
	gcc util.c dijkstra.c -std=c99 -o ../build/dijkstra.out

spfa: spfa.c util.c
	gcc util.c spfa.c -std=c99 -o ../build/spfa.out

astar: astar.c util.c
	gcc util.c astar.c -std=c99 -o ../build/astar.out
