pacman: util.c pacman.c
	gcc util.c pacman.c -o ../build/pacman.out -std=c99

pacman2: util.c pacman2.c
	gcc pacman2.c bits/graph.c bits/methods.c bits/queue.c bits/search.c  util.c -o ../build/pacman2.out -std=c99

